<?
$PERM["/"]["2"]="D";
$PERM["/"]["13"]="T_10";
$PERM["/"]["12"]="R";
$PERM["/"]["*"]="D";
$PERM["workgroups"]["G12"]="R";
$PERM["workgroups"]["G16"]="X";
$PERM["workgroups"]["G14"]="X";
$PERM["workgroups"]["*"]="D";
$PERM["workgroups"]["G13"]="D";
$PERM["extranet"]["12"]="T_8";
$PERM["extranet"]["19"]="T_10";
$PERM["extranet"]["18"]="T_8";
$PERM["extranet"]["17"]="T_8";
$PERM["extranet"]["*"]="D";
$PERM["upload"]["17"]="T_8";
$PERM["upload"]["*"]="R";
$PERM["upload"]["5"]="T_8";
$PERM["crm"]["16"]="X";
$PERM["about"]["9"]="T_9";
$PERM["company"]["9"]="T_9";
$PERM["apconnect"]["*"]="R";
$PERM["marketplace"]["*"]="R";
$PERM["pub"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
?>